const Product = [

  {
    id: "4501200",
    name: "PAMP سبيكة ذهب 1 جرام",
    category: "bars",
    subCategory: "sw-bars", 
    cat:"sw",
    price: 363 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبائك ذهب سويسرية، مستطيلة الشكل، عالية النقاوة بنسبة 999.9 ذهب صافي",
    image: "https://ounce.com.sa/wp-content/uploads/2022/09/AU00RI001S101_14.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501201",
    name: "PAMP سبيكة ذهب 2.5 جرام",
    category: "bars",
    subCategory: "sw-bars", 
    cat:"sw",
    price: 825 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبائك ذهب سويسرية، مستطيلة الشكل، عالية النقاوة بنسبة 999.9 ذهب صافي",
    image: "https://ounce.com.sa/wp-content/uploads/2021/11/front2_63_4-1-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501202",
    name: "PAMP سبيكة ذهب 5 جرام",
    category: "bars",
    subCategory: "sw-bars", 
    cat:"sw",
    price: 1485  ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبائك ذهب سويسرية، مستطيلة الشكل، عالية النقاوة بنسبة 999.9 ذهب صافي",
    image: "https://ounce.com.sa/wp-content/uploads/2021/11/5-FRONT--768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501203",
    name: "PAMP سبيكة ذهب 10 جرام",
    category: "bars",
    subCategory: "sw-bars", 
    cat:"sw",
    price: 2750 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبائك ذهب سويسرية، مستطيلة الشكل، عالية النقاوة بنسبة 999.9 ذهب صافي",
    image: "https://ounce.com.sa/wp-content/uploads/2021/11/10-SWIS.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501204",
    name: "PAMP سبيكة ذهب 20 جرام",
    category: "bars",
    subCategory: "sw-bars", 
    cat:"sw",
    price: 4840 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبائك ذهب سويسرية، مستطيلة الشكل، عالية النقاوة بنسبة 999.9 ذهب صافي",
    image: "https://ounce.com.sa/wp-content/uploads/2021/11/20-FRONT.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501205",
    name: "PAMP سبيكة ذهب 31.1 جرام",
    category: "bars",
    subCategory: "sw-bars", 
    cat:"sw",
    price: 7800 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبائك ذهب سويسرية، مستطيلة الشكل، عالية النقاوة بنسبة 999.9 ذهب صافي",
    image: "https://ounce.com.sa/wp-content/uploads/2021/11/romanesque-cross-gold-177555.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501206",
    name: "PAMP سبيكة ذهب 50 جرام",
    category: "bars",
    subCategory: "sw-bars", 
    cat:"sw",
    price: 11880 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبائك ذهب سويسرية، مستطيلة الشكل، عالية النقاوة بنسبة 999.9 ذهب صافي",
    image: "https://ounce.com.sa/wp-content/uploads/2022/07/Pamp-Suisse-50-gram-Gold.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501207",
    name: "PAMP سبيكة ذهب 100 جرام",
    category: "bars",
    subCategory: "sw-bars", 
    cat:"sw",
    price: 23760 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبائك ذهب سويسرية، مستطيلة الشكل، عالية النقاوة بنسبة 999.9 ذهب صافي",
    image: "https://ounce.com.sa/wp-content/uploads/2021/11/100-FRONT-.jpg",
    capacity:"",
    color:"",
  },
  
  

  {
    id: "4501003",
    name: "سبيكة ذهب 1 جرام",
    category: "bars",
    subCategory: "sa-bars-gold",   
    cat:"sa",
    price: 307 ,
    weight:"1 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/14-768x768.png",
    capacity:"",
    color:"",
  },
  {
    id: "4501002",
    name: "سبيكة ذهب 2.5 جرام",
    category: "bars",
    subCategory: "sa-bars-gold",   
    cat:"sa",
    price: 739,
    weight:"2.5",
    height:"2CM",
    witdh:"1.1CM ",
    caliber:" 24 قيراط",
    cuntryMk:"سعودية",
    avilabel:"",
    description: "سبائك ذهب سعودية، مستطيلة الشكل، عالية النقاوة بنسبة 999.9 ذهب صافي",
    image: "https://ounce.com.sa/wp-content/uploads/2020/12/33-2-768x768.jpg",
    capacity:"",
    color:"",
  },
  
  {
    id: "4501004",
    name: "سبيكة ذهب 5 جرام",
    category: "bars",
    subCategory: "sa-bars-gold",   
    cat:"sa",
    price: 1281,
    weight:"5 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/13-768x768.png",
    capacity:"",
    color:"",
  },
  {
    id: "4501005",
    name: "سبيكة ذهب 10 جرام",
    category: "bars",
    subCategory: "sa-bars-gold",   
    cat:"sa",
    price: 2431,
    weight:"10 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/12-768x768.png",
    capacity:"",
    color:"",
  },
  {
    id: "4501006",
    name: "سبيكة ذهب 20 جرام",
    category: "bars",
    subCategory: "sa-bars-gold",   
    cat:"sa",
    price: 4687,
    weight:"20 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/27-768x768.png",
    capacity:"",
    color:"",
  },
  {
    id: "4501007",
    name: "سبيكة ذهب 31.1 جرام",
    category: "bars",
    subCategory: "sa-bars-gold",   
    cat:"sa",
    price: 7288,
    weight:"31.1 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/28.png",
    capacity:"",
    color:"",
  },
  {
    id: "4501008",
    name: "سبيكة ذهب 50 جرام",
    category: "bars",
    subCategory: "sa-bars-gold",   
    cat:"sa",
    price: 11607,
    weight:" 50 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/29-768x768.png",
    capacity:"",
    color:"",
  },
  {
    id: "4501009",
    name: "سبيكة ذهب 100 جرام",
    category: "bars",
    subCategory: "sa-bars-gold",   
    cat:"sa",
    price: 22995,
    weight:"100 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "– التصميم : طبعة سويسريه شكل العروسه أو الورده",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/30-768x768.png",
    capacity:"",
    color:"",
  },
  {
    id: "4501010",
    name: "سبيكة ذهب 1 كيلو",
    category: "bars",
    subCategory: "sa-bars-gold",   
    cat:"sa",
    price: 227760,
    weight:"1000 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/kilo-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501011",
    name: "سبيكة ذهب بيضاوي 5.2 جرام",
    category: "bars",
    subCategory: "sa-bars-oval", 
    cat:"sa",

    price: 1332,
    weight:"5 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/19-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501012",
    name: "سبيكة ذهب 10.2 جرام",
    category: "bars",
    subCategory: "sa-bars-oval", 
    cat:"sa",
    price: 2480,
    weight:"10 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/19.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501013",
    name: "سبيكة ذهب 15.85 جرام",
    category: "bars",
    subCategory: "sa-bars-oval", 
    cat:"sa",
    price: 3714,
    weight:"15 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/19-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501014",
    name: "سبيكة ذهب 20.3 جرام",
    category: "bars",
    subCategory: "sa-bars-oval", 
    cat:"sa",
    price: 4757,
    weight:"20 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/19-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501015",
    name: "سبيكة ذهب 31.4 جرام",
    category: "bars",
    subCategory: "sa-bars-oval", 
    cat:"sa",
    price: 7289,
    weight:"31.1 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/19-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501016",
    name: "سبيكة ذهب 2.5 جرام",
    category: "bars",
    subCategory: "ua-bars-gold-oval", 
    cat:"ua",
    price: 739 ,
    weight:"2.5 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/ittihad-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501017",
    name: "سبيكة ذهب 5 جرام",
    category: "bars",
    subCategory: "ua-bars-gold-oval", 
    cat:"ua",
    price: 1303,
    weight:" 5 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/ittihad-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501018",
    name: "سبيكة ذهب 10 جرام",
    category: "bars",
    subCategory: "ua-bars-gold-oval", 
    cat:"ua",
    price: 2453,
    weight:"10 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/ittihad-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501019",
    name: "سبيكة ذهب 15.55 جرام",
    category: "bars",
    subCategory: "ua-bars-gold-oval", 
    cat:"ua",
    price: 3746 ,
    weight:" 15 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/ittihad-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501020",
    name: "سبيكة ذهب 20 جرام",
    category: "bars",
    subCategory: "ua-bars-gold-oval", 
    cat:"ua",
    price: 4717,
    weight:"20 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/ittihad-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501021",
    name: "سبيكة ذهب 31.1 جرام",
    category: "bars",
    subCategory: "ua-bars-gold-oval", 
    cat:"ua",
    price: 7267,
    weight:"31 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/ittihad-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501023",
    name: "سبيكة ذهب 1 جرام",
    category: "bars",
    subCategory: "ua-bars-gold", 
    cat:"ua",
    price: 337 ,
    weight:" 1 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/20-1-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501024",
    name: "سبيكة ذهب 5 جرام",
    category: "bars",
    subCategory: "ua-bars-gold", 
    cat:"ua",
    price: 1259,
    weight:" 5 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/21-1-768x768.jpg",
    capacity:"",
    color:"",
  },
 
  
  {
    id: "4501025",
    name: "سبيكة ذهب 10 جرام",
    category: "bars",
    subCategory: "ua-bars-gold", 
    cat:"ua",
    price: 2431,
    weight:"10 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/22-1-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501022",
    name: "سبيكة ذهب 15.55 جرام",
    category: "bars",
    subCategory: "ua-bars-gold", 
    cat:"ua",
    price: 3678,
    weight:"15.55 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/12/halftroyounce-768x768.jpg",
    capacity:"",
    color:"",
  },
 
  {
    id: "4501026",
    name: "سبيكة ذهب 20 جرام",
    category: "bars",
    subCategory: "ua-bars-gold", 
    cat:"ua",
    price: 4652,
    weight:"",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/23-1-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501027",
    name: "سبيكة ذهب 31.1 جرام",
    category: "bars",
    subCategory: "ua-bars-gold", 
    cat:"ua",
    price: 7220,
    weight:"31.1 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/24-1.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501028",
    name: "سبيكة ذهب 50 جرام",
    category: "bars",
    subCategory: "ua-bars-gold", 
    cat:"ua",
    price: 11519,
    weight:"50 جرام",
    height:"",
    witdh:"",
    caliber:"24 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "سبيكة ذهبية مستطيلة عالية النقاوهة عيار 24 قيراط بنسبة نقاء 999,9 ذهب صافي.",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/25-1.jpg",
    capacity:"",
    color:"",
  },

  {
    id: "4501030",
    name: "جنيه بريطاني 8 جرام",
    category: "coins",
    subCategory: "en-coins",
    price: 2073,
    weight:"8 جرام",
    height:"",
    witdh:"",
    caliber:"22 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/Untitled-design-6-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501031",
    name: "جنيه سعودي 8 جرام",
    category: "coins",
    subCategory: "sa-coins",
    price: 2073,
    weight:"8 جرام",
    height:"",
    witdh:"",
    caliber:"22 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/6-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501032",
    name: "ربع جنيه سعودي 2 جرام",
    category: "coins",
    subCategory: "sa-coins",
    price: 641 ,
    weight:"2 جرام",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/09/s2.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501033",
    name: "نص جنيه سعودي 4 جرام",
    category: "coins",
    subCategory: "sa-coins",
    price: 1078,
    weight:"4 جرام",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/11/6-1-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501040",
    name: "برواز جنيه وزن من 5.36 – 5.62 عيار 21",
    category: "framesnecklaces",
    subCategory: "frames-gold",
    price: 1843,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2022/02/SR5-768x960.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501041",
    name: "برواز جنيه وزن من 5.4 – 5.57 عيار 21",
    category: "framesnecklaces",
    subCategory: "frames-gold",
    price: 1857,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2022/02/SR4-768x960.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501042",
    name: "برواز جنيه وزن من 6.62 – 7.05 عيار 21",
    category: "framesnecklaces",
    subCategory: "frames-gold",
    price: 2253,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2022/02/SR2-768x960.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501043",
    name: "برواز جنيه وزن من 8.06 – 8.40 عيار 21",
    category: "framesnecklaces",
    subCategory: "frames-gold",
    price: 2575,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2022/02/SR1-768x960.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501044",
    name: "برواز جنيه وزن من 7.78 – 8.06 عيار 21",
    category: "framesnecklaces",
    subCategory: "frames-gold",
    price: 2575,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2022/02/SR3-768x960.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501045",
    name: "برواز سبيكة وزن من 8.53 – 9.37 عيار 21",
    category: "framesnecklaces",
    subCategory: "frames-gold",
    price: 2882,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2022/02/PAMP-FR-10G-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501046",
    name: "برواز سبيكة وزن من 8.47 – 9.45 عيار 21",
    category: "framesnecklaces",
    subCategory: "frames-gold",
    price: 2882,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2022/02/PAMP-FR10-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501047",
    name: "برواز سبيكة وزن من 9.9 – 10.62 عيار 21",
    category: "framesnecklaces",
    subCategory: "frames-gold",
    price: 3219,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2022/02/PAMP-F-20G-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501048",
    name: "برواز سبيكة أونصة PAMP وزن من 15.09 – 16.56 عيار 21",
    category: "framesnecklaces",
    subCategory: "frames-gold",
    price: 4971 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2022/02/PAMP-FRAME-314-scaled.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501049",
    name: "برواز سبيكة أونصة PAMP وزن من 14.74 – 16.36 عيار 21",
    category: "framesnecklaces",
    subCategory: "frames-gold",
    price: 4971,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2022/02/PAMP-FRAM-31.g-768x960.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501050",
    name: "سلسال ذهب عيار 21 طول 40 سم وزن 1.95 جرام",
    category: "framesnecklaces",
    subCategory: "necklaces-gold",
    price: 692 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/12/P10015-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501051",
    name: "سلسال ذهب عيار 21 طول 60 سم وزن 2.68 جرام",
    category: "framesnecklaces",
    subCategory: "necklaces-gold",
    price: 803 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/12/P10017-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501052",
    name: "سلسال ذهب عيار 21 وزن 2.6 جرام طول 40 سم",
    category: "framesnecklaces",
    subCategory: "necklaces-gold",
    price: 866 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/12/P10016-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501053",
    name: "سلسال ذهب طول 60 سم وزن 3.3 جرام",
    category: "framesnecklaces",
    subCategory: "necklaces-gold",
    price: 952 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/12/kOLSYFOQ-768x960.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501054",
    name: "سلسال ذهب عيار 21 طول 50 سم",
    category: "framesnecklaces",
    subCategory: "necklaces-gold",
    price: 1067,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/12/P10018-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501055",
    name: "سلسال ذهب طول 70 سم وزن 3.9 جرام",
    category: "framesnecklaces",
    subCategory: "necklaces-gold",
    price: 1082,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/12/P10019-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501056",
    name: "سلسال ذهب عيار 21 طول 70 سم وزن 5.5 جرام",
    category: "framesnecklaces",
    subCategory: "necklaces-gold",
    price: 1465 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2020/12/P10019-768x768.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501057",
    name: "سلسال ذهب عيار 21 طول 50 سم",
    category: "framesnecklaces",
    subCategory: "necklaces-gold",
    price: 3463,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LCH-768x960.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501058",
    name: "سلسال ذهب عيار 21 طول 60 سم",
    category: "framesnecklaces",
    subCategory: "necklaces-gold",
    price: 4040,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LCH60-768x960.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501060",
    name: "أسوارة جنيهات ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 334 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBJ1015....-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501061",
    name: "أسوارة جنيهات ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 343 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LABJ1014.j-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501062",
    name: "أسوارة جنيهات ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 837 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBJ1016...-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501063",
    name: "أسوارة ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 1156 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBG1007..g-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501064",
    name: "أسوارة جنيهات ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 1530,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBJ1001.-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501065",
    name: "أسوارة جنيهات ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 1616,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBJ1003..-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501066",
    name: "أسوارة ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 1738 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBG1006.-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501067",
    name: "أسوارة جنيهات ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 1832,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBJ1012.j...-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501068",
    name: "أسوارة جنزير ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 1876,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBG1009.j-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501069",
    name: "أسوارة جنزير ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 1903,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBG1008.j.-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501070",
    name: "أسوارة جنيهات ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 2497,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBJ1004...-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501071",
    name: "أسوارة جنيهات ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "bracelets",
    price: 2762,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/LBJ1013....-min-768x614.jpg",
    capacity:"",
    color:"",
  },
  {
    id: "4501080",
    name: "تعليقة ذهب طبعة جنيه عيار 21",
    category: "braceletnecklace",
    subCategory: "necklace",
    price: 455 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/DSC05365-min-768x960.jpg",
    capacity:"",
    color:"",
   },
  {
    id: "4501081",
    name: "تشوكر جنيهات ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "necklace",
    price: 739 ,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/DSC05315-copy-min-768x960.jpg",
    capacity:"",
    color:"",
   },
  {
    id: "4501082",
    name: "عقد جنيهات ذهب عيار21",
    category: "braceletnecklace",
    subCategory: "necklace",
    price: 1049,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/DSC05353-copy-min-768x960.jpg",
    capacity:"",
    color:"",
   },
  {
    id: "4501083",
    name: "عقد جنيهات ذهب عيار21",
    category: "braceletnecklace",
    subCategory: "necklace",
    price: 1049,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/DSC05353-copy-min-768x960.jpg",
    capacity:"",
    color:"",
   },
  {
    id: "4501084",
    name: "تشوكر جنيهات ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "necklace",
    price: 1455,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/DSC05332-copy-min-768x960.jpg",
    capacity:"",
    color:"",
   },
  {
    id: "4501085",
    name: "عقد جنيهات ذهب عيار21",
    category: "braceletnecklace",
    subCategory: "necklace",
    price: 1797,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/DSC05337-copy-min-768x960.jpg",
    capacity:"",
    color:"",
   },
  {
    id: "4501086",
    name: "عقد جنيهات ذهب عيار21",
    category: "braceletnecklace",
    subCategory: "necklace",
    price: 1876,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/DSC05343-copy-min-768x960.jpg",
    capacity:"",
    color:"",
   },
  {
    id: "4501087",
    name: "عقد ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "necklace",
    price: 3981,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/DSC05360-copy-min-1-768x960.jpg",
    capacity:"",
    color:"",
   },
  {
    id: "4501088",
    name: "عقد ذهب عيار 21",
    category: "braceletnecklace",
    subCategory: "necklace",
    price: 4229,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/DSC_8743-copy-min-768x960.jpg",
    capacity:"",
    color:"",
   },
  {
    id: "4501089",
    name: "عقد جنيهات ذهب عيار21",
    category: "braceletnecklace",
    subCategory: "necklace",
    price: 5327,
    weight:"",
    height:"",
    witdh:"",
    caliber:"21 قيراط",
    cuntryMk:"",
    avilabel:"",
    description: "",
    image: "https://ounce.com.sa/wp-content/uploads/2021/03/DSC05347-copy-min-768x960.jpg",
    
   },
];

const braceletnecklace = Product.filter((i) => i.category === "braceletnecklace");
const necklace = Product.filter((i) => i.subCategory === "necklace");
const bracelet = Product.filter((i) => i.subCategory === "bracelet");

const framesnecklaces = Product.filter((i) => i.category === "framesnecklaces");
const frames = Product.filter((i) => i.subCategory === "frames-gold");
const necklacesGold = Product.filter((i) => i.subCategory === "necklaces-gold");

const bars = Product.filter((i) => i.category === "bars");
const uaBars = Product.filter((i) => i.subCategory === "ua-bars-gold");
const saBarsGold = Product.filter((i) => i.subCategory === "sa-bars-gold");
const saBarsOval = Product.filter((i) => i.subCategory === "sa-bars-oval");
const saBars=  Product.filter((i) => i.cat === "sa");
const swBars = Product.filter((i) => i.subCategory === "sw-bars");

const coins = Product.filter((i) => i.category === "coins");
const enCoins = Product.filter((i) => i.subCategory === "en-coins");
const saCoins = Product.filter((i) => i.subCategory === "sa-coins");


module.exports = {
  braceletnecklace,
  necklace,
  bracelet,
  framesnecklaces,
  frames,
  necklacesGold,
  bars,
  uaBars,
  saBars,
  coins,
  enCoins,
  saCoins,
  swBars,
  saBarsGold,
  saBarsOval,
  Product
};
